In [2]:
import tensorflow as tf
print(tf.__version__)

2.10.0


# Define the constant A Tensor with the given Matrix

In [36]:
#Create tensors using tf.constant()
A = tf.constant([[[275,879,231,495,367],
                      [959,333,757,300,456],
                      [234,907,806,867,375]]], shape=[3, 5])

In [37]:
A

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[275, 879, 231, 495, 367],
       [959, 333, 757, 300, 456],
       [234, 907, 806, 867, 375]])>

In [38]:
A.shape

TensorShape([3, 5])

# Define the constant B Tensor with the given Matrix

In [39]:
B = tf.constant([[[58,23,45,34],
                  [45,45,67,98],
                  [56,67,73,60],
                  [87,87,94,46],
                  [59,97,67,71]
                 ]], shape=[5, 4])

In [33]:
B

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[58, 23, 45, 34],
       [45, 45, 67, 98],
       [56, 67, 73, 60],
       [87, 87, 94, 46],
       [59, 97, 67, 71]])>

In [29]:
B.shape

TensorShape([5, 4])

# Multiply the tensors A & B

In [47]:
C = A @ B

In [48]:
C

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[133159, 140021, 159250, 158179],
       [166003, 158093, 179479, 156836],
       [197077, 212003, 236760, 211709]])>

# We can't multiply tensors B @ A as the tensor B := TensorShape([5, 4]) is incompatiable for multiplication operation with tensor A := TensorShape([3, 5]). The multiplication is possible only when the number of columns of Tensor B is equal to the number of rows of Tensor A. 